export const USERS_REQUEST='USER_REQUEST'
export const USERS_SUCCESS='USER_SUCCESS'
export const USERS_FAILURE='USER_FAILURE'
export const USERS_UPDATE="USER_UPDATE"
export const USERS_DELETE="USER_DELETE"
export const USERS_ADD="USER_ADD"