//TODO AUTH REDUCER

export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';

export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAILURE = 'REGISTER_FAILURE';


//TODO PRODUCT CRUD REDUCER

export const GET_PRODUCT_SUCCESS='GET_PRODUCT_SUCCESS';

export const GET_PRODUCT_FAILURE='GET_PRODUCT_FAILURE';

export const GET_PRODUCT_REQUEST='GET_PRODUCT_REQUEST';

export const GET_PRODUCTBY_ID_SUCCESS='GET_PRODUCTBY_ID_SUCCESS';

export const ADD_PRODUCT_SUCCESS='ADD_PRODUCT_SUCCESS';

export const DETETE_PRODUCT_SUCCESS='DETETE_PRODUCT_SUCCESS';

export const EDIT_PRODUCT_SUCCESS='EDIT_PRODUCT_SUCCESS';

//TODO LOADING 

export const LOADING='LOADING_REQUEST';

//TODO CART 

export const ADD_TO_CART='ADD_TO_CART';

export const CART_ITEM='CART_ITEM';

